kind: ConfigMap
apiVersion: v1
metadata:
  name: module-camel
data:
  module-camel.json: |
    {
      "apiVersion": "argoproj.io/v1alpha1",
      "kind": "Application",
      "metadata": {
        "name": "{{ .Values.module.module_camel.name }}",
        "namespace": "{{ .Values.module.module_camel.namespace }}",
        "finalizers": [
          "resources-finalizer.argocd.argoproj.io/foreground"
        ]
      },
      "spec": {
        "destination": {
          "name": "",
          "namespace": "{{ .Values.module.module_camel.destination.namespace }}",
          "server": "https://kubernetes.default.svc"
        },
        "project": "default",
        "syncPolicy": {
          "automated": {
            "prune": false,
            "selfHeal": false
          }
        },
        "source": {
          "repoURL": "{{ .Values.module.module_camel.source.repoUrl }}",
          "targetRevision": "{{ .Values.module.module_camel.source.targetRevision }}",
          "path": "{{ .Values.module.module_camel.source.path }}",
          "helm": {
            "valuesObject": {
              "minio": {
                "minio": {
                  "accessKey": "minio",
                  "secretKey": "minio123",
                  "region": "us-east-1"
                },
                "route": {
                  "host": "minio-globex-camel-{{ .Values.variable.user }}.{{ .Values.openshift.domain }}"
                }
              },
              "kafka": {
                "kafka": {
                  "namespace": "globex-mw-{{ .Values.variable.user }}"
                }
              },
              "amq-broker": {
                "amq": {
                  "namespace": "camel-common"
                }
              },
              "globex-web": {
                "globexStoreApp": {
                  "url": "http://globex-store-app.globex-{{ .Values.variable.user }}:8080"
                },
                "activityTrackingService": {
                  "url": "http://activity-tracking.globex-{{ .Values.variable.user }}:8080"
                },
                "recommendationEngine": {
                  "url": "http://recommendation-engine.globex-{{ .Values.variable.user }}:8080"
                },
                "globexSupportUrl": {
                  "url": "http://globex-support:80"
                },
                "sso": {
                  "url": "https://sso.{{ .Values.openshift.domain }}/realms/globex-{{ .Values.variable.user }}",
                  "client": "globex-web-gateway",
                  "logoutUri": "https://globex-web-globex-camel-{{ .Values.variable.user }}.{{ .Values.openshift.domain }}/home"
                }
              },
              "matrix-secret": {
                "matrix": {
                  "namespace": "camel-common",
                  "url": "http://matrix-synapse.camel-common.svc.cluster.local:8008"
                }
              },
              "matrix-integration": {
                "deploy": false,
                "rocketchat": {
                  "channel": "globex-support-{{ .Values.variable.user }}"
                }
              },
              "globex-support-integration": {
                "deploy": false
              },
              "transcript-integration": {
                "deploy": false
              }
            }
          }
        }
      }
    }