kind: ConfigMap
apiVersion: v1
metadata:
  name: module-serverless
data:
  module-serverless.json: |
    {
      "apiVersion": "argoproj.io/v1alpha1",
      "kind": "Application",
      "metadata": {
        "name": "{{ .Values.module.module_serverless.name }}",
        "namespace": "{{ .Values.module.module_serverless.namespace }}",
        "finalizers": [
          "resources-finalizer.argocd.argoproj.io/foreground"
        ]
      },
      "spec": {
        "ignoreDifferences": [
          {
            "group": "serving.knative.dev",
            "kind": "Service",
            "jsonPointers": [
              "/spec/template/spec/containers/0/name",
              "/spec/template/spec/containers/0/env"
            ]
          }
        ],
        "destination": {
          "name": "",
          "namespace": "{{ .Values.module.module_serverless.destination.namespace }}",
          "server": "https://kubernetes.default.svc"
        },
        "project": "default",
        "syncPolicy": {
          "automated": {
            "prune": false,
            "selfHeal": false
          }
        },
        "source": {
          "repoURL": "{{ .Values.module.module_serverless.source.repoUrl }}",
          "targetRevision": "{{ .Values.module.module_serverless.source.targetRevision }}",
          "path": "{{ .Values.module.module_serverless.source.path }}",
          "helm": {
            "valuesObject": {
              "kafka": {
                "namespace": "globex-mw-{{ .Values.variable.user }}",
                "bootstrapServer": "kafka-kafka-bootstrap.globex-mw-{{ .Values.variable.user }}.svc.cluster.local:9092"
              },
              "kafka-topics": {
                "kafka": {
                  "namespace": "globex-mw-{{ .Values.variable.user }}",
                  "cluster": "kafka"
                }
              },
              "kafka-secret": {
                "kafka": {
                  "namespace": "globex-mw-{{ .Values.variable.user }}"
                }
              },
              "knative-kafkasink": {
                "kafka": {
                  "bootstrapServer": "kafka-kafka-bootstrap.globex-mw-{{ .Values.variable.user }}.svc.cluster.local:9092"
                }
              },
              "knative-kafkasource": {
                "kafka": {
                  "bootstrapServer": "kafka-kafka-bootstrap.globex-mw-{{ .Values.variable.user }}.svc.cluster.local:9092"
                }
              },
              "product-reviews": {
                "kafkaSink": {
                  "reviews": "${K_SINK}"
                }
              },
              "aiml-moderate-reviews": {
                "gunicorn": {
                  "threads": "4",
                  "timeout": "180"
                }
              },
              "aiml-sentiment-reviews": {
                "gunicorn": {
                  "threads": "4",
                  "timeout": "180"
                }
              },
              "globex-web-reviews": {
                "globexStoreApp": {
                  "url": "http://globex-store-app.globex-{{ .Values.variable.user }}.svc.cluster.local:8080"
                },
                "activityTrackingService": {
                  "url": "http://activity-tracking.globex-{{ .Values.variable.user }}.svc.cluster.local:8080",
                  "service": "activity-tracking",
                  "path": "/track"
                },
                "recommendationEngine": {
                  "url": "http://recommendation-engine.globex-{{ .Values.variable.user }}.svc.cluster.local:8080",
                  "service": "recommendation-engine",
                  "path": "/score/product"
                },
                "productReviews": {
                  "url": "http://product-reviews.{{ .Values.module.module_serverless.destination.namespace }}.svc.cluster.local:8080",
                  "submitReviewPath": "/review/submit",
                  "fetchReviewPath": "/review/list"
                },
                "sso": {
                  "url": "https://sso.{{ .Values.openshift.domain }}/realms/globex-{{ .Values.variable.user }}",
                  "client": "globex-web-gateway",
                  "logoutUri": "https://globex-web-{{ .Values.module.module_serverless.destination.namespace }}.{{ .Values.openshift.domain }}/home"
                }
              }             
            }
          }
        }
      }
    }