apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "workshop-deployer.name" . }}
  labels:
    {{- include "workshop-deployer.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "workshop-deployer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "workshop-deployer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "workshop-deployer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: BOOKBAG_NAMESPACE
              value: {{ .Values.bookbag.namespace}}
            - name: ALLOWED_MODULES_COUNT
              value: {{ .Values.modules.maxCount }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: oauth-proxy
          args:
            - --provider=openshift
            - --https-address=:8888
            - --http-address=
            - --email-domain=*
            - --upstream=http://localhost:8080
            - --tls-cert=/etc/tls/private/tls.crt
            - --tls-key=/etc/tls/private/tls.key
            - --cookie-secret-file=/etc/proxy/secrets/session_secret
            - --openshift-service-account={{ include "workshop-deployer.serviceAccountName" . }}
            - --openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            - --skip-auth-regex=^/metrics
            - --pass-access-token=true
          image: {{ .Values.oauthProxy.image.repository }}:{{ .Values.oauthProxy.image.tag }}
          imagePullPolicy: {{ .Values.oauthProxy.image.pullPolicy }}
          ports:
            - name: oauth-proxy
              containerPort: 8888
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/tls/private
              name: secret-workshop-deployer-tls
            - mountPath: /etc/proxy/secrets
              name: secret-workshop-deployer-proxy
      volumes:
        - name: secret-workshop-deployer-tls
          secret:
            defaultMode: 420
            secretName: {{ include "workshop-deployer.name" . }}-tls
        - name: secret-workshop-deployer-proxy
          secret:
            defaultMode: 420
            secretName: {{ include "workshop-deployer.name" . }}-proxy
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
